name: Docker Build and Push

on:
  push:
    branches: [ main ]

jobs:
  docker-build-push:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Build and Push Docker Image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: cocktail-nextjs-repo:${{ github.sha }}
        registry: 010130764883.dkr.ecr.us-east-1.amazonaws.com
        dockerfile: frontend/cocktails/Dockerfile
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}